### PR TITLE
Inherit documentation from `gg_blanket()`

### PR DESCRIPTION
**Pull request by olivroy**
Closes #625 

ggridges is in Suggests, no need to repeat it in `Config/Needs/website`.

pkgdown dep is in the gh action, no need to declare it again here.

`viridis::mako()`  is just reexported from viridisLite.

Here is the script I used for doing it faster.

```r
file_names <- fs::dir_ls("R", regexp = "gg_") |> 
  fs::path_filter(regexp = "blanket", invert = TRUE)

file_names |> 
  purrr::map(readLines) |> 
  purrr::map(\(x) tibble::enframe(x, name = "line", value = "content")) |> 
  dplyr::bind_rows(.id = "file") |> 
  dplyr::filter(!stringr::str_detect(content, "@param")) |> 
  dplyr::reframe(
    content = list(content),
    .by = file
  ) |> 
  dplyr::pull() |> 
  purrr::set_names(file_names) |> 
  purrr::iwalk(\(x, name) writeLines(text = x, con = name))

purrr::walk(file_names,  \(x) rstudioapi::documentOpen
            (x, line = 5))
```

After this PR, you will no longer need to copy and paste documentation around, only need to update it in a single place, and after `devtools::document()`, it will get updated everywhere.

### CODE REVIEW

**Comment by davidhodge931** [comment]
Awesome, thanks so much @olivroy :)

I've been wanting to know how to do this for ages!

**Comment by olivroy** [comment]
Glad it helps! Cheers

**Comment by davidhodge931** [comment]
Oh one thing: I just noticed that now the Rstudio autocomplete now seems not able to autocomplete the variable names from a dataset? Any ideas?

image

**Comment by davidhodge931** [comment]
Ignore me - it was because I was using palmerpenguins::penguins rather than loading the library first

**Comment by olivroy** [comment]
Sure, no problem. The only thing to watch out for will be if the parameters of a function are not updated the same as the other.

`devtools::check_man()` can be handy to detect that everything is correct (as well as github actions and R CMD CHECK of course).

**Comment by davidhodge931** [comment]
If you any other ideas or thoughts about how to improve the package, let me know. 

I'm planning on releasing once ggplot2 does, and then after that I'll try to keep things stable and not break the API (unless it's a _very_ good idea!)

**Comment by olivroy** [comment]
Sure! I'll check! 

If you can merge dev in main, I think it would be helpful! I am not very good with git either, and working on dev is more difficult, no CI , no website update etc.

**Comment by davidhodge931** [comment]
Cool, I'll merge it in - people might get a bit confused where the website relates to the DEV version instead of CRAN, but it's only temporary

**Comment by davidhodge931** [comment]
Just pushed - the updated articles explain things a lot better what the package is actually doing than previously. I just haven't yet really described how the package supports alpha yet. This latest version 6 is a _massive_ update

**Comment by davidhodge931** [comment]
Do you know why I need to depend on >= 4.2.0 of R, @olivroy? 

I had thought it was much more backwards compatible than that. 

I might as well change the %>% to |>, if it's not compatible further back...

**Comment by olivroy** [comment]
Oops, sorry I made a mistake. It actually requires R 4.1.0 due to the base pipe `|>` and the short anonymous function syntax `\(x) x`.

If you revert to magrittr pipe and `function(x) x`, this is no longer needed.

**Comment by davidhodge931** [comment]
Ah okay, the base |> is currently only currently used in the examples and vignettes.

I'll change the \(x) to function(x) in the `gg_blanket` code and then I can take off the >= 4.1.0?

**Comment by olivroy** [comment]
I think that makes sense!

**Comment by davidhodge931** [comment]
I guess it is compatible with 3.5.0, which is what ggplot2 and dplyr are compatible with - but not sure exactly

Think I'll just remove the Depends line..

**Pull request merged**
