### PR TITLE
Inherit documentation from `gg_blanket()`

### PR DESCRIPTION
**Pull request by olivroy**
This will allow to change documentation in a single place and it will update everywhere else.

For example if you want to change the documentation of the `stat` parameter for a single function, it will be easier and be more obvious.

See https://roxygen2.r-lib.org/articles/reuse.html for more details.

I re-documented and everything seemed fine

Dependency on R 4.2 is due to the use of shortcut anonymous functions `\(x) x ^2`

### CODE REVIEW

**Comment by davidhodge931** [comment]
Thanks @olivroy 

Would inheriting the params in this way affect the auto-complete in Rstudio??

**Comment by olivroy** [comment]
No, not at all. the man gets generated independently for all functions. 

See that `dplyr::slice_*()` functions inherit their documentation from https://github.com/tidyverse/dplyr/blob/HEAD/R/slice.R from arrange and filter but end users don't see that.

**Comment by olivroy** [comment]
Also, if you want to develop on the main branch and want to test against dev ggplot2.

We can use this 
`usethis::use_dev_package("ggplot2", "3.5.0", remote = "tidyverse/ggplot2#5592")`

**Comment by davidhodge931** [comment]
Sorry @olivroy I had some work in progress when you did this PR, which I've just pushed. Are you able  to resolve these new  conflicts, and then I can merge it in? I'm still a bit of an amateur with git, and not super confident with resolving conflicts etc.

Also, why did you remove ggridges from Config/Needs/website? I have a ggridges example in an article, so I think I need it referenced here to make any CRAN note go away

**Comment by davidhodge931** [comment]
One other thing: each non-gg_blanket function needs to inherit all gg_blanket params _except_ geom - as this argument is locked for the non-gg_blanket functions

Is there a way to do this? I think maybe I saw this done somewhere with a minus symbol??

**Comment by olivroy** [comment]
`@inheritParams` will only inherit for the arguments that are present. Since `gg_label()` and friends do not have a `geom` param, it is not inherited.

**Comment by olivroy** [comment]
The - symbol is for the `@inheritDotParams` tag.

**Pull request closed without merging**
